// AUTO-GENERATED by laranja — do not edit. Regenerated on deploy/synth/diff.
import type {
  LaranjaConfig,
  HttpResourceConfig,
  CronResourceConfig,
  QueueResourceConfig,
} from "@alzulejos/laranja-core";

/** The HTTP app id, if this project serves one. */
export type HttpResourceId = "http";
/** Cron ids in this project. */
export type CronResourceId = "clearCacheCron" | "sendOnboardingEmailsCron";
/** Queue names in this project. */
export type QueueResourceId = "fifoHandler.fifo" | "welcomeEmail" | "welcomeEmailDLQ";

/** Every resource id: the http id, cron ids, and queue names. */
export type ResourceId = HttpResourceId | CronResourceId | QueueResourceId;

/**
 * LaranjaConfig with `resources` keys checked against your real resources, and
 * each key typed to its kind — so a queue DLQ requires `maxReceiveCount` and a
 * cron knob can't be set on a queue.
 */
export type TypedLaranjaConfig = Omit<LaranjaConfig, "resources"> & {
  resources?: Partial<Record<HttpResourceId, HttpResourceConfig>> &
    Partial<Record<CronResourceId, CronResourceConfig>> &
    Partial<Record<QueueResourceId, QueueResourceConfig>>;
};
