// AUTO-GENERATED by laranja — do not edit. Regenerated on deploy/synth/diff.
import type { LaranjaConfig, ResourceConfig } from "@alzulejos/laranja-core";

/** Resource ids in this project: the http id, cron ids, and queue names. */
export type ResourceId = "clearCacheCron" | "eventHandler" | "eventsHandlerDLQ" | "fifoHandler.fifo" | "http" | "sendOnboardingEmailsCron";

/** LaranjaConfig with `resources` keys checked against your real resources. */
export type TypedLaranjaConfig = Omit<LaranjaConfig, "resources"> & {
  resources?: Partial<Record<ResourceId, ResourceConfig>>;
};
