import path from "node:path";
import { handlerLabel, handlerName, type InfraIR } from "@laranja/core";
import { generateEntries } from "@laranja/runtime";
import { renderAwsSchedule } from "./schedule-aws.js";

/** A file to write, with its path relative to the eject dir. */
export interface EjectedFile {
  path: string;
  contents: string;
}

export interface EjectOptions {
  /** Absolute path to the user's project root. */
  projectDir: string;
  /** Absolute path to the dir the CDK project will be written to (e.g. <project>/infra). */
  ejectDir: string;
  stackName: string;
  region?: string;
  /** Version range for @laranja/runtime in the ejected package.json. */
  runtimeVersion?: string;
}

function pascal(s: string): string {
  return s
    .replace(/(^|[^A-Za-z0-9])([A-Za-z0-9])/g, (_m, _sep, ch: string) => ch.toUpperCase())
    .replace(/[^A-Za-z0-9]/g, "");
}

/** CloudFormation-safe construct id fragment. */
function cid(s: string): string {
  return s.replace(/[^A-Za-z0-9]/g, "");
}

/**
 * Generate a standalone, editable CDK project from the Infra IR. This is the
 * "eject" output — the user owns it and deploys with plain `cdk deploy`. Uses
 * NodejsFunction so the entry shims bundle themselves at synth time (no laranja
 * build tooling needed).
 */
export function generateEjectProject(ir: InfraIR, opts: EjectOptions): EjectedFile[] {
  const files: EjectedFile[] = [];
  const className = `${pascal(opts.stackName)}Stack`;
  const stackFileBase = `${opts.stackName.replace(/[^A-Za-z0-9_-]/g, "-")}-stack`;
  const runtimeVersion = opts.runtimeVersion ?? "^0.1.0";

  // Reuse the exact same entry shims; they become owned source under entries/.
  const entries = generateEntries(ir, {
    projectDir: opts.projectDir,
    entryDir: path.join(opts.ejectDir, "entries"),
  });
  for (const e of entries) {
    files.push({ path: `entries/${e.fileName}`, contents: e.contents });
  }
  const entryFileById = new Map(entries.map((e) => [e.id, e.fileName]));

  // ---- lib/<name>-stack.ts ----
  const lines: string[] = [];
  lines.push(`// Generated by \`laranja eject\` — this file is YOURS to edit.`);
  lines.push(`import path from "node:path";`);
  lines.push(`import { fileURLToPath } from "node:url";`);
  lines.push(`import { CfnOutput, Duration, Stack, type StackProps } from "aws-cdk-lib";`);
  lines.push(
    ir.http
      ? `import { FunctionUrlAuthType, HttpMethod, Runtime } from "aws-cdk-lib/aws-lambda";`
      : `import { Runtime } from "aws-cdk-lib/aws-lambda";`,
  );
  lines.push(`import { NodejsFunction } from "aws-cdk-lib/aws-lambda-nodejs";`);
  lines.push(`import { Rule, Schedule } from "aws-cdk-lib/aws-events";`);
  lines.push(`import { LambdaFunction as LambdaTarget } from "aws-cdk-lib/aws-events-targets";`);
  lines.push(`import { Queue, QueueEncryption } from "aws-cdk-lib/aws-sqs";`);
  lines.push(`import { SqsEventSource } from "aws-cdk-lib/aws-lambda-event-sources";`);
  lines.push(`import type { Construct } from "constructs";`);
  lines.push("");
  lines.push(`const __dirname = path.dirname(fileURLToPath(import.meta.url));`);
  // Config statics are inlined; code-discovered env("...") keys are read from
  // the environment at `cdk deploy` time (you own this project now).
  if (ir.envKeys.length) {
    lines.push(`const ENV: Record<string, string> = {`);
    lines.push(`  ...${JSON.stringify(ir.env)},`);
    lines.push(`  ...Object.fromEntries(${JSON.stringify(ir.envKeys)}.map((k) => [k, process.env[k] ?? ""])),`);
    lines.push(`};`);
  } else {
    lines.push(`const ENV: Record<string, string> = ${JSON.stringify(ir.env)};`);
  }
  lines.push(`const APP = ${JSON.stringify(ir.app.name)};`);
  lines.push(`const STAGE = ${JSON.stringify(ir.app.stage)};`);
  lines.push("// Physical Lambda name: <app>-<label>-<stage>");
  lines.push("const fnName = (label: string) =>");
  lines.push("  `${APP}-${label}-${STAGE}`.replace(/[^A-Za-z0-9-_]/g, \"-\").slice(0, 64);");
  lines.push("");
  lines.push(`export class ${className} extends Stack {`);
  lines.push(`  constructor(scope: Construct, id: string, props?: StackProps) {`);
  lines.push(`    super(scope, id, props);`);
  lines.push("");
  lines.push(`    const lambda = (cid: string, label: string, entry: string, timeout: number) =>`);
  lines.push(`      new NodejsFunction(this, cid, {`);
  lines.push(`        functionName: fnName(label),`);
  lines.push(`        runtime: Runtime.NODEJS_20_X,`);
  lines.push(`        entry: path.join(__dirname, "..", "entries", entry),`);
  lines.push(`        handler: "handler",`);
  lines.push(`        timeout: Duration.seconds(timeout),`);
  lines.push(`        environment: ENV,`);
  lines.push(`        bundling: { externalModules: ["@aws-sdk/*"], tsconfig: path.join(__dirname, "..", "tsconfig.json") },`);
  lines.push(`      });`);
  lines.push("");

  // HTTP (skipped for workers-only apps)
  if (ir.http) {
    lines.push(`    // --- HTTP: proxy Lambda + Function URL ---`);
    lines.push(`    const httpFn = lambda("HttpFn", "app", ${JSON.stringify(entryFileById.get("http"))}, 30);`);
    lines.push(`    const httpUrl = httpFn.addFunctionUrl({`);
    lines.push(`      authType: FunctionUrlAuthType.NONE,`);
    lines.push(`      cors: { allowedOrigins: ["*"], allowedMethods: [HttpMethod.ALL], allowedHeaders: ["*"] },`);
    lines.push(`    });`);
    lines.push(`    new CfnOutput(this, "HttpUrl", { value: httpUrl.url });`);
    lines.push("");
  }

  // Cron
  if (ir.crons.length > 0) lines.push(`    // --- Cron: Lambda + EventBridge rule each ---`);
  ir.crons.forEach((cron, i) => {
    const v = `cron${i}`;
    const label = handlerLabel(cron);
    lines.push(`    const ${v} = lambda("Cron${cid(cron.id)}Fn", ${JSON.stringify(label)}, ${JSON.stringify(entryFileById.get(cron.id))}, 60);`);
    lines.push(`    new Rule(this, "Cron${cid(cron.id)}Rule", {`);
    lines.push(`      schedule: Schedule.expression(${JSON.stringify(renderAwsSchedule(cron.schedule))}),`);
    lines.push(`      targets: [new LambdaTarget(${v})],`);
    lines.push(`    });`);
  });
  if (ir.crons.length > 0) lines.push("");

  // Queues
  if (ir.queues.length > 0) lines.push(`    // --- Queues: SQS + consumer Lambda each ---`);
  ir.queues.forEach((q, i) => {
    const qv = `queue${i}`;
    const cv = `consumer${i}`;
    lines.push(`    const ${qv} = new Queue(this, "Queue${cid(q.id)}", {`);
    lines.push(`      queueName: ${JSON.stringify(q.name)},`);
    if (q.fifo) {
      lines.push(`      fifo: true,`);
      lines.push(`      contentBasedDeduplication: true,`);
    }
    lines.push(`      encryption: QueueEncryption.SQS_MANAGED,`);
    lines.push(`      visibilityTimeout: Duration.seconds(180),`);
    lines.push(`    });`);
    lines.push(`    const ${cv} = lambda("Consumer${cid(q.id)}Fn", ${JSON.stringify(handlerName(q))}, ${JSON.stringify(entryFileById.get(q.id))}, 30);`);
    lines.push(`    ${cv}.addEventSource(new SqsEventSource(${qv}, { batchSize: ${q.batchSize ?? 10}, reportBatchItemFailures: true }));`);
    lines.push(`    new CfnOutput(this, "Queue${cid(q.id)}Url", { value: ${qv}.queueUrl });`);
  });

  lines.push(`  }`);
  lines.push(`}`);
  lines.push("");
  files.push({ path: `lib/${stackFileBase}.ts`, contents: lines.join("\n") });

  // ---- bin/app.ts ----
  const envArg = opts.region ? ` env: { region: ${JSON.stringify(opts.region)} } ` : "";
  files.push({
    path: "bin/app.ts",
    contents: `import { App } from "aws-cdk-lib";
import { ${className} } from "../lib/${stackFileBase}.js";

const app = new App();
new ${className}(app, ${JSON.stringify(opts.stackName)}, {${envArg}});
app.synth();
`,
  });

  // ---- cdk.json ----
  files.push({ path: "cdk.json", contents: `${JSON.stringify({ app: "npx tsx bin/app.ts" }, null, 2)}\n` });

  // ---- package.json ----
  const pkg = {
    name: `${opts.stackName}-infra`,
    private: true,
    version: "0.0.0",
    type: "module",
    scripts: { synth: "cdk synth", deploy: "cdk deploy", destroy: "cdk destroy" },
    dependencies: {
      "@laranja/runtime": runtimeVersion,
      "aws-cdk-lib": "^2.160.0",
      constructs: "^10.3.0",
    },
    devDependencies: {
      "aws-cdk": "^2.160.0",
      esbuild: "^0.28.1",
      tsx: "^4.19.0",
      typescript: "^5.6.2",
    },
  };
  files.push({ path: "package.json", contents: `${JSON.stringify(pkg, null, 2)}\n` });

  // ---- tsconfig.json ----
  const tsconfig = {
    compilerOptions: {
      target: "ES2022",
      module: "NodeNext",
      moduleResolution: "NodeNext",
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      experimentalDecorators: true,
      emitDecoratorMetadata: true,
    },
  };
  files.push({ path: "tsconfig.json", contents: `${JSON.stringify(tsconfig, null, 2)}\n` });

  // ---- README.md ----
  files.push({
    path: "README.md",
    contents: `# ${opts.stackName} — ejected infrastructure

This CDK project was generated by \`laranja eject\`. It is **yours** — edit it freely.

\`\`\`bash
cd infra
npm install
npm run deploy      # cdk deploy
\`\`\`

- \`lib/${stackFileBase}.ts\` — the stack (Lambdas, Function URL, cron rules, queues).
- \`entries/\` — the Lambda entry shims (also yours to edit).

You no longer need the laranja CLI to deploy this.
`,
  });

  return files;
}
