import type { InfraIR } from "@alzulejos/laranja-core";

/**
 * The resource-key ids in a project: "http" (when there's an HTTP app), each
 * cron's id, and each queue's name. This is the one namespace that `resources`
 * overrides and DLQ references address — sorted + de-duplicated.
 */
export function resourceIds(ir: InfraIR): string[] {
  return dedupeSort([
    ...(ir.http ? ["http"] : []),
    ...ir.crons.map((c) => c.id),
    ...ir.queues.map((q) => q.name),
  ]);
}

/** `"a" | "b"` from ids, or `never` when there are none. */
function unionOf(ids: string[]): string {
  return ids.length > 0 ? ids.map((id) => JSON.stringify(id)).join(" | ") : "never";
}

function dedupeSort(ids: string[]): string[] {
  return [...new Set(ids)].sort();
}

/**
 * Generate the contents of the project's `laranja.types.ts` — the resource‑id
 * unions plus a `TypedLaranjaConfig` alias that maps each key to the right override
 * shape. Post‑consolidation a Nest module is one Lambda, so compute lives on a
 * `WorkerId` (module) key while a grouped cron/queue key only takes its trigger
 * knobs; a standalone handler (Express / function‑style) is its own Lambda and
 * keeps compute + trigger. Opting in (typing the config with `TypedLaranjaConfig`)
 * turns a mistyped id, a compute knob on a grouped handler, or a queue DLQ missing
 * `maxReceiveCount` into a compile‑time error with autocomplete.
 */
export function generateResourceTypes(ir: InfraIR): string {
  const grouped = <T extends { workersId?: string }>(xs: T[], on: boolean) =>
    xs.filter((x) => Boolean(x.workersId) === on);
  return render({
    http: unionOf(ir.http ? ["http"] : []),
    worker: unionOf(dedupeSort((ir.workers ?? []).map((w) => w.id))),
    groupedCron: unionOf(dedupeSort(grouped(ir.crons, true).map((c) => c.id))),
    standaloneCron: unionOf(dedupeSort(grouped(ir.crons, false).map((c) => c.id))),
    groupedQueue: unionOf(dedupeSort(grouped(ir.queues, true).map((q) => q.name))),
    standaloneQueue: unionOf(dedupeSort(grouped(ir.queues, false).map((q) => q.name))),
  });
}

/**
 * The stub written by `init`, before any scan has discovered resources. `string`
 * keeps `resources` permissive (any key, compute + trigger) until the first
 * deploy/synth narrows it.
 */
export function generateResourceTypesStub(): string {
  return render({
    http: "string",
    worker: "never",
    groupedCron: "never",
    standaloneCron: "string",
    groupedQueue: "never",
    standaloneQueue: "string",
  });
}

interface Ids {
  http: string;
  worker: string;
  groupedCron: string;
  standaloneCron: string;
  groupedQueue: string;
  standaloneQueue: string;
}

function render(ids: Ids): string {
  return `// AUTO-GENERATED by laranja — do not edit. Regenerated on deploy/synth/diff.
import type {
  LaranjaConfig,
  HttpResourceConfig,
  WorkerResourceConfig,
  CronResourceConfig,
  CronTriggerConfig,
  QueueResourceConfig,
  QueueTriggerConfig,
} from "@alzulejos/laranja-core";

/** The HTTP app id, if this project serves one. */
export type HttpResourceId = ${ids.http};
/** Worker module ids — each is ONE Lambda; set compute (memory/timeout/…) here. */
export type WorkerId = ${ids.worker};
/** Cron ids that share a worker module's Lambda (trigger knobs only). */
type GroupedCronId = ${ids.groupedCron};
/** Cron ids that are their own Lambda (Express / function-style): compute + trigger. */
type StandaloneCronId = ${ids.standaloneCron};
/** Queue names that share a worker module's Lambda (trigger knobs only). */
type GroupedQueueId = ${ids.groupedQueue};
/** Queue names that are their own Lambda (Express / function-style): compute + trigger. */
type StandaloneQueueId = ${ids.standaloneQueue};

/** Cron ids in this project. */
export type CronResourceId = GroupedCronId | StandaloneCronId;
/** Queue names in this project (also the valid DLQ targets). */
export type QueueResourceId = GroupedQueueId | StandaloneQueueId;

/** Every resource id: the http id, worker ids, cron ids, and queue names. */
export type ResourceId = HttpResourceId | WorkerId | CronResourceId | QueueResourceId;

/**
 * LaranjaConfig with \`resources\` keys checked against your real resources. Compute
 * lives on a worker module key; a grouped cron/queue takes only its trigger knobs
 * (compute there is a compile error pointing at the module); a standalone handler
 * takes compute + trigger. A queue DLQ requires \`maxReceiveCount\`.
 */
export type TypedLaranjaConfig = Omit<LaranjaConfig, "resources"> & {
  resources?: Partial<Record<HttpResourceId, HttpResourceConfig>> &
    Partial<Record<WorkerId, WorkerResourceConfig>> &
    Partial<Record<GroupedCronId, CronTriggerConfig<QueueResourceId>>> &
    Partial<Record<StandaloneCronId, CronResourceConfig<QueueResourceId>>> &
    Partial<Record<GroupedQueueId, QueueTriggerConfig<QueueResourceId>>> &
    Partial<Record<StandaloneQueueId, QueueResourceConfig<QueueResourceId>>>;
};
`;
}
