import type { InfraIR } from "@alzulejos/laranja-core";

/**
 * The resource-key ids in a project: "http" (when there's an HTTP app), each
 * cron's id, and each queue's name. This is the one namespace that `resources`
 * overrides and DLQ references address — sorted + de-duplicated.
 */
export function resourceIds(ir: InfraIR): string[] {
  return dedupeSort([
    ...(ir.http ? ["http"] : []),
    ...ir.crons.map((c) => c.id),
    ...ir.queues.map((q) => q.name),
  ]);
}

/** `"a" | "b"` from ids, or `never` when there are none. */
function unionOf(ids: string[]): string {
  return ids.length > 0 ? ids.map((id) => JSON.stringify(id)).join(" | ") : "never";
}

function dedupeSort(ids: string[]): string[] {
  return [...new Set(ids)].sort();
}

/**
 * Generate the contents of the project's `laranja.types.ts` — per-kind
 * `ResourceId` unions plus a `TypedLaranjaConfig` alias that maps each id to the
 * override shape for its kind. Opting in (typing the config with
 * `TypedLaranjaConfig`) turns a mistyped resource id, a knob used on the wrong
 * kind, or a queue DLQ missing `maxReceiveCount` into a compile-time error with
 * autocomplete — instead of only the scan-time hard error.
 */
export function generateResourceTypes(ir: InfraIR): string {
  return render({
    http: unionOf(ir.http ? ["http"] : []),
    cron: unionOf(dedupeSort(ir.crons.map((c) => c.id))),
    queue: unionOf(dedupeSort(ir.queues.map((q) => q.name))),
  });
}

/**
 * The stub written by `init`, before any scan has discovered resources. `string`
 * keeps `resources` permissive (any key) until the first deploy/synth narrows it.
 */
export function generateResourceTypesStub(): string {
  return render({ http: "string", cron: "string", queue: "string" });
}

function render(ids: { http: string; cron: string; queue: string }): string {
  return `// AUTO-GENERATED by laranja — do not edit. Regenerated on deploy/synth/diff.
import type {
  LaranjaConfig,
  HttpResourceConfig,
  CronResourceConfig,
  QueueResourceConfig,
} from "@alzulejos/laranja-core";

/** The HTTP app id, if this project serves one. */
export type HttpResourceId = ${ids.http};
/** Cron ids in this project. */
export type CronResourceId = ${ids.cron};
/** Queue names in this project. */
export type QueueResourceId = ${ids.queue};

/** Every resource id: the http id, cron ids, and queue names. */
export type ResourceId = HttpResourceId | CronResourceId | QueueResourceId;

/**
 * LaranjaConfig with \`resources\` keys checked against your real resources, and
 * each key typed to its kind — so a queue DLQ requires \`maxReceiveCount\` and a
 * cron knob can't be set on a queue.
 */
export type TypedLaranjaConfig = Omit<LaranjaConfig, "resources"> & {
  resources?: Partial<Record<HttpResourceId, HttpResourceConfig>> &
    Partial<Record<CronResourceId, CronResourceConfig<QueueResourceId>>> &
    Partial<Record<QueueResourceId, QueueResourceConfig<QueueResourceId>>>;
};
`;
}
