import type { InfraIR } from "@alzulejos/laranja-core";

/**
 * The resource-key ids in a project: "http" (when there's an HTTP app), each
 * cron's id, and each queue's name. This is the one namespace that `resources`
 * overrides and DLQ references address — sorted + de-duplicated.
 */
export function resourceIds(ir: InfraIR): string[] {
  const ids = [
    ...(ir.http ? ["http"] : []),
    ...ir.crons.map((c) => c.id),
    ...ir.queues.map((q) => q.name),
  ];
  return [...new Set(ids)].sort();
}

/**
 * Generate the contents of the project's `laranja.types.ts` — a `ResourceId`
 * union of the real ids plus a `TypedLaranjaConfig` alias that narrows
 * `resources` keys to that union. Opting in (typing the config with
 * `TypedLaranjaConfig`) turns a mistyped resource id into a compile-time error
 * with autocomplete, instead of only the scan-time hard error.
 */
export function generateResourceTypes(ir: InfraIR): string {
  const ids = resourceIds(ir);
  // `never` (no resources) makes `resources` an empty object — but scan already
  // rejects an empty project, so in practice there is always at least one id.
  const union = ids.length > 0 ? ids.map((id) => JSON.stringify(id)).join(" | ") : "never";
  return render(union);
}

/**
 * The stub written by `init`, before any scan has discovered resources. `string`
 * keeps `resources` permissive (any key) until the first deploy/synth narrows it.
 */
export function generateResourceTypesStub(): string {
  return render("string");
}

function render(union: string): string {
  return `// AUTO-GENERATED by laranja — do not edit. Regenerated on deploy/synth/diff.
import type { LaranjaConfig, ResourceConfig } from "@alzulejos/laranja-core";

/** Resource ids in this project: the http id, cron ids, and queue names. */
export type ResourceId = ${union};

/** LaranjaConfig with \`resources\` keys checked against your real resources. */
export type TypedLaranjaConfig = Omit<LaranjaConfig, "resources"> & {
  resources?: Partial<Record<ResourceId, ResourceConfig>>;
};
`;
}
