import type { ServiceDecl, ServicesConfig } from "@alzulejos/laranja-core";
import { deriveDbName, deriveSecret, type DevServiceState } from "./state.js";

/** Default image tags, kept in one place so a version bump is one edit. */
const POSTGRES_VERSION = 16;
const REDIS_VERSION = 7;

/**
 * Render a docker-compose project for the declared services.
 *
 * Emitted as a file (rather than driven through `docker run`) so the user can
 * read exactly what we started, and so `docker compose down` remains a valid
 * escape hatch if the CLI is ever unavailable to them.
 */
export function renderCompose(
  projectId: string,
  services: ServicesConfig,
  state: Record<string, DevServiceState>,
): string {
  const blocks: string[] = [];
  const volumes: string[] = [];

  for (const [key, service] of Object.entries(services)) {
    const s = state[key];
    if (!s) continue;
    blocks.push(renderService(projectId, key, service, s));
    volumes.push(`  ${s.volume}:\n    name: ${s.volume}`);
  }

  return [
    "# Generated by `laranja dev`. Edits are overwritten on the next run.",
    "services:",
    blocks.join("\n"),
    "volumes:",
    volumes.join("\n"),
    "",
  ].join("\n");
}

function renderService(
  projectId: string,
  key: string,
  service: ServiceDecl,
  state: DevServiceState,
): string {
  // Bind to 127.0.0.1, never 0.0.0.0: these carry derived (i.e. predictable)
  // credentials, so they must not be reachable from the local network.
  const bind = (port: number) => `      - "127.0.0.1:${state.port}:${port}"`;

  if (service.kind === "postgres") {
    const version = service.version ?? POSTGRES_VERSION;
    return [
      `  ${key}:`,
      `    image: postgres:${version}-alpine`,
      `    container_name: ${state.container}`,
      "    restart: unless-stopped",
      "    environment:",
      "      POSTGRES_USER: laranja",
      `      POSTGRES_PASSWORD: ${deriveSecret(projectId, key, "password")}`,
      `      POSTGRES_DB: ${deriveDbName(key)}`,
      "    ports:",
      bind(5432),
      "    volumes:",
      `      - ${state.volume}:/var/lib/postgresql/data`,
      "    healthcheck:",
      `      test: ["CMD-SHELL", "pg_isready -U laranja -d ${deriveDbName(key)}"]`,
      "      interval: 2s",
      "      timeout: 3s",
      "      retries: 30",
    ].join("\n");
  }

  const version = service.version ?? REDIS_VERSION;
  return [
    `  ${key}:`,
    `    image: valkey/valkey:${version}-alpine`,
    `    container_name: ${state.container}`,
    "    restart: unless-stopped",
    // appendonly is NOT optional here: local queues live in this Redis (db 1),
    // so without persistence a container restart silently drops every queued
    // message — the exact failure a developer would blame on their own code.
    '    command: ["valkey-server", "--appendonly", "yes"]',
    "    ports:",
    bind(6379),
    "    volumes:",
    `      - ${state.volume}:/data`,
    "    healthcheck:",
    '      test: ["CMD", "valkey-cli", "ping"]',
    "      interval: 2s",
    "      timeout: 3s",
    "      retries: 30",
  ].join("\n");
}
